version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_V}
    volumes:
      - post_db:/data/db
    networks:
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    build: ../src/ui
    image: ${USERNAME}/ui:${UI_V}
    ports:
      - ${APP_PORT}:9292/tcp
    networks:
      - front_net
  post:
    build: ../src/post-py
    image: ${USERNAME}/post:${POST_V}
    networks:
      - front_net
      - back_net
  comment:
    build: ../src/comment
    image: ${USERNAME}/comment:${COMMENT_V}
    networks:
      - front_net
      - back_net

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - front_net
      - back_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net

  mongo-exporter:
    image: percona/mongodb_exporter:2.37.0
    networks:
      - back_net
    command:
      - '--mongodb.uri=mongodb://post_db:27017'

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.23.0
    networks:
      - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
